spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:~/tmp/customer # (1)
    username: massan
    password: massan
  jpa:
    hibernate.ddl-auto: validate # (2)
  thymeleaf.cache: false